### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by rsoorajs** [kingsman96/translator-bot#1]
every time i try to translate,i am getting some error.please fix it  asap

`'NoneType' object has no attribute 'group'`

![IMG_20210211_221402_374](https://user-images.githubusercontent.com/20116017/107668255-7b18c280-6cb6-11eb-888d-51ae5c458c3b.jpg)

**Comment by kingsman96** [comment]
This error comes from the library used to translate. Googletrans no longer works because, most likely, google has blocked the use of that token. The solution is to get a new token to translate or rely on another API. asap i will fix it.

**Comment by rsoorajs** [comment]
> This error comes from the library used to translate. Googletrans no longer works because, most likely, google has blocked the use of that token. The solution is to get a new token to translate or rely on another API. asap i will fix it.

thank you..please mention here after you fixed it..

**Comment by rsoorajs** [comment]
> This error comes from the library used to translate. Googletrans no longer works because, most likely, google has blocked the use of that token. The solution is to get a new token to translate or rely on another API. asap i will fix it.

this one will work


https://github.com/Saravananslb/py-googletranslation

**Comment by kingsman96** [comment]
2021-02-14: code fixed, thanks to @telegrambotdev.
